include: package:lint/package.yaml

linter:
  rules:
    parameter_assignments: false
    avoid_print: false
    avoid_double_and_int_checks: false
    avoid_classes_with_only_static_members: false
    avoid_redundant_argument_values: false
    missing_whitespace_between_adjacent_strings: false
    cast_nullable_to_non_nullable: false
