name: propertylistserialization
description: iOS compatible plist serialization and deserialization library for Dart.
version: 1.4.0
homepage: https://github.com/electricbolt/dartpropertylistserialization

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  xml: ^6.5.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.8
