name: propertylistserialization
description: iOS compatible plist serialization and deserialization library for Dart.
version: 1.3.0
homepage: https://github.com/electricbolt/dartpropertylistserialization

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  convert: ^3.1.0
  xml: ^6.0.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.24.0
